### ISSUE TITLE
scripts/examples.py

### ISSUE THREAD

**Issue by LinYuechen** [eth-sri/language-model-arithmetic#3]
(model_arithmetic) root@interactive24814:/opt/data/private/model_arithmetic# python scripts/examples.py
2024-03-06 11:07:19.313409: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-06 11:07:19.315727: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-06 11:07:19.353537: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-06 11:07:19.353942: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-06 11:07:20.087168: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /cardiffnlp/tweet-topic-21-multi/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7188795990>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 16b7d3d9-ef71-4a45-94d0-b4f5632abd63)')' thrown while requesting HEAD https://huggingface.co/cardiffnlp/tweet-topic-21-multi/resolve/main/tokenizer_config.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /cardiffnlp/tweet-topic-21-multi/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7188795660>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 6448c92a-002e-4dda-b6c0-a83d72c0dc42)')' thrown while requesting HEAD https://huggingface.co/cardiffnlp/tweet-topic-21-multi/resolve/main/config.json
Traceback (most recent call last):
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/data/private/model_arithmetic/scripts/examples.py", line 95, in <module>
    C_educational = Classifier(M, "cardiffnlp/tweet-topic-21-multi", prompt_template=lambda e, f: "",
  File "/opt/data/private/model_arithmetic/src/model_arithmetic/runnable_operators.py", line 698, in __init__
    self.tokenizer = load_tokenizer(self.model)
  File "/opt/data/private/model_arithmetic/src/model_arithmetic/basic_model_loader.py", line 39, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 701, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1023, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/miniconda3/envs/model_arithmetic/lib/python3.10/site-packages/transformers/utils/hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like cardiffnlp/tweet-topic-21-multi is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by JasperDekoninck** [comment]
From the error, it seems that you were offline when running the code. Specifically, 
> Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

seems to indicate that there was some problem with connecting to Huggingface. The model you tried to download [is still available](https://huggingface.co/cardiffnlp/tweet-topic-21-multi), so either try again when your internet is working or download the model in some other way on your machine.

Hope that fixes it!
